Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,3 +1,5 @@
+# This is a basic workflow to help you get started with Actions
+
 name: LibClang tutorial
 
 on:
@@ -13,16 +15,17 @@ jobs:
     steps:
       - uses: actions/checkout@v2
 
-      # Install LLVM system-wide using GitHub llvm-util
-      - name: Install LLVM system-wide
+      # Install LLVM system-wide using GitHub utility
+      - name: Install LLVM
         run: |
           curl -fsSL -o "LLVM-18.1.0-win64.exe" "https://github.com/llvm/llvm-project/releases/download/llvmorg-18.1.0/LLVM-18.1.0-win64.exe"
-          ./LLVM-18.1.0-win64.exe /S
-
-      # Manually set llvm-config path
-      - name: Set llvm-config path
-        run: |
-          $llvmConfigPath = "C:\Program Files\LLVM\bin\llvm-config.exe"
+          LLVM-18.1.0-win64.exe /S
+          # Assuming the default installation path for LLVM
+          $llvmConfigPath = "C:\\Program Files\\LLVM\\bin\\llvm-config.exe"
+          if (!(Test-Path $llvmConfigPath)) {
+            echo "llvm-config.exe not found at $llvmConfigPath"
+            exit 1
+          }
           echo "LLVM_CONFIG_EXECUTABLE=$llvmConfigPath" | Out-File -FilePath $env:GITHUB_ENV -Append
           echo "PATH=$(dirname $llvmConfigPath);$env:Path" | Out-File -FilePath $env:GITHUB_ENV -Append
 
